package ch.abbaye11.adsbservice.domaine.sbs1;

import java.util.Arrays;

public enum SBS1MessageType {
    SEL("SELECTION CHANGE MESSAGE","Generated when the user changes the selected aircraft in BaseStation"),
    ID("NEW ID MESSAGE","Generated when an aircraft being tracked sets or changes its callsign"),
    AIR("NEW AIRCRAFT MESSAGE","Generated when the SBS picks up a signal for an aircraft that it isn't currently tracking"),
    STA("STATUS CHANGE MESSAGE","Generated when an aircraft's status changes according to the time-out values in the Data Settings menu"),
    CLK("CLICK MESSAGE","Generated when the user double-clicks (or presses return) on an aircraft"),
    MSG("TRANSMISSION MESSAGE","Generated by the aircraft. There are eight different MSG types.");

    private final String nom;
    private final String description;

    SBS1MessageType(String nom, String description){
        this.nom = nom;
        this.description = description;
    }


    public static SBS1MessageType fromString(String sbs1Element) {
        return Arrays.stream(SBS1MessageType.values()).filter(messageType -> {
            return messageType.name().equals(sbs1Element);
        }).findFirst().orElseThrow(() ->
                new SBS1MessageException("Can't parse value " + sbs1Element + "for mapping message type")
        );
    }


}
