adsb:
    tcp:
        endpoint:
            host: localhost
            port: 1234

mongodb:
    host: localhost
    port: 27017
    database: adsb
    collection: message-11

spring:
    profiles:
        active: file

    kafka:
        bootstrap-servers: localhost:9092
        topic: test-22